"""Export attacks as pytest test files."""

import ast
from pathlib import Path


def export_tests(attacks: list, output_path: str) -> int:
    """Export successful attacks as pytest file.

    Args:
        attacks: List of Attack objects with test_code, description, attack_type
        output_path: Path where to save the pytest file

    Returns:
        Number of tests exported
    """
    if not attacks:
        return 0

    # Validate all test codes before writing
    valid_attacks = []
    for attack in attacks:
        try:
            ast.parse(attack.test_code)
            valid_attacks.append(attack)
        except SyntaxError:
            # Skip invalid syntax
            continue

    if not valid_attacks:
        return 0

    # Generate pytest file content
    lines = []

    # Header with imports
    lines.append('"""')
    lines.append("Auto-generated pytest file from adversarial attacks.")
    lines.append("Generated by RedGuard Code Hardening.")
    lines.append('"""')
    lines.append("")
    lines.append("import pytest")
    lines.append("")

    # Add each test
    for attack in valid_attacks:
        # Add comment with attack info
        lines.append(f"# Attack type: {attack.attack_type}")
        lines.append(f"# Description: {attack.description}")

        # Add test code
        lines.append(attack.test_code)
        lines.append("")

    # Write to file
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    content = "\n".join(lines)
    output_file.write_text(content)

    return len(valid_attacks)
